version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: UTC
  open-pull-requests-limit: 6
- package-ecosystem: npm
  directories:
    - "/"
    - "/clients/js"
  schedule:
    interval: daily
    time: "09:00"
    timezone: UTC
  open-pull-requests-limit: 6
